# Generated by Django 2.1.3 on 2018-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkateApp', '0006_auto_20181204_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='avatar'),
        ),
    ]
