# Generated by Django 2.1.3 on 2018-12-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkateApp', '0009_auto_20181205_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='warn',
            field=models.IntegerField(default=0),
        ),
    ]
